In [25]:
import tensorflow as tf
import os
import keras.backend as K
import pandas as pd
from tensorflow.keras.models import Sequential
from keras.layers import Dense
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, BatchNormalization, LeakyReLU, GlobalAveragePooling2D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Conv2D, MaxPooling2D, SpatialDropout2D, MaxPool2D
from sklearn.model_selection import train_test_split
from tensorflow.keras.applications import VGG16
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.preprocessing.image import img_to_array
import numpy as np
import cv2

In [26]:
cars = pd.read_csv(r"C:\Users\Carlos M\Pictures\cars.csv")
cars

,filename,Start X,Start Y,W,H,data
0,2Q__ (1).jpg,1,26,97,49,"x"":1,""y"":26,""width"":97,""height"":49}"
1,2Q__ (3).jpg,5,11,296,120,"{""name"":""rect"",""x"":5,""y"":11,""width"":296,""heigh..."
2,2Q__ (4).jpg,22,27,223,142,"{""name"":""rect"",""x"":22,""y"":27,""width"":223,""heig..."
3,2Q__ (5).jpg,33,15,246,127,"{""name"":""rect"",""x"":33,""y"":15,""width"":246,""heig..."
4,2Q__ (6).jpg,13,42,233,124,"{""name"":""rect"",""x"":13,""y"":42,""width"":233,""heig..."
5,9k_ (2).jpg,4,55,217,141,"{""name"":""rect"",""x"":4,""y"":55,""width"":217,""heigh..."
6,9k_ (3).jpg,22,18,228,128,"{""name"":""rect"",""x"":22,""y"":18,""width"":228,""heig..."
7,9k_ (4).jpg,35,29,229,124,"{""name"":""rect"",""x"":35,""y"":29,""width"":229,""heig..."
8,9k_ (6).jpg,19,37,234,116,"{""name"":""rect"",""x"":19,""y"":37,""width"":234,""heig..."
9,9k_ (7).jpg,24,57,205,101,"{""name"":""rect"",""x"":24,""y"":57,""width"":205,""heig..."
10,9k_ (8).jpg,15,13,262,145,"{""name"":""rect"",""x"":15,""y"":13,""width"":262,""heig..."
11,9k_ (10).jpg,70,24,196,106,"{""name"":""rect"",""x"":70,""y"":24,""width"":196,""heig..."
12,9k_ (11).jpg,57,51,161,101,"{""name"":""rect"",""x"":57,""y"":51,""width"":161,""heig..."
13,images (18).jpg,38,34,254,113,"{""name"":""rect"",""x"":38,""y"":34,""width"":254,""heig..."
14,images (19).jpg,46,52,185,110,"{""name"":""rect"",""x"":46,""y"":52,""width"":185,""heig..."
15,images (20).jpg,23,18,228,116,"{""name"":""rect"",""x"":23,""y"":18,""width"":228,""heig..."
16,images (21).jpg,85,49,158,92,"{""name"":""rect"",""x"":85,""y"":49,""width"":158,""heig..."
17,images (22).jpg,42,104,157,110,"{""name"":""rect"",""x"":42,""y"":104,""width"":157,""hei..."
18,images (23).jpg,42,32,214,114,"{""name"":""rect"",""x"":42,""y"":32,""width"":214,""heig..."
19,images (24).jpg,9,23,259,154,"{""name"":""rect"",""x"":9,""y"":23,""width"":259,""heigh..."
20,images (25).jpg,19,9,222,163,"{""name"":""rect"",""x"":19,""y"":9,""width"":222,""heigh..."
21,images (26).jpg,78,37,211,116,"{""name"":""rect"",""x"":78,""y"":37,""width"":211,""heig..."
22,images (28).jpg,17,20,276,120,"{""name"":""rect"",""x"":17,""y"":20,""width"":276,""heig..."
23,images (29).jpg,49,2,239,158,"{""name"":""rect"",""x"":49,""y"":2,""width"":239,""heigh..."
24,images (31).jpg,73,8,192,139,"{""name"":""rect"",""x"":73,""y"":8,""width"":192,""heigh..."
25,images (32).jpg,6,11,284,143,"{""name"":""rect"",""x"":6,""y"":11,""width"":284,""heigh..."
26,images (34).jpg,10,72,206,102,"{""name"":""rect"",""x"":10,""y"":72,""width"":206,""heig..."
27,images (35).jpg,42,45,212,112,"{""name"":""rect"",""x"":42,""y"":45,""width"":212,""heig..."
28,images (37).jpg,21,37,232,121,"{""name"":""rect"",""x"":21,""y"":37,""width"":232,""heig..."
29,images (38).jpg,14,16,267,142,"{""name"":""rect"",""x"":14,""y"":16,""width"":267,""heig..."
30,images (39).jpg,23,44,179,111,"{""name"":""rect"",""x"":23,""y"":44,""width"":179,""heig..."
31,images (40).jpg,49,42,198,109,"{""name"":""rect"",""x"":49,""y"":42,""width"":198,""heig..."
32,Z (6).jpg,32,21,253,123,"{""name"":""rect"",""x"":32,""y"":21,""width"":253,""heig..."
33,Z (7).jpg,28,35,224,133,"{""name"":""rect"",""x"":28,""y"":35,""width"":224,""heig..."
34,Z (8).jpg,27,34,209,105,"{""name"":""rect"",""x"":27,""y"":34,""width"":209,""heig..."

In [27]:
Xmin = cars["Start X"].to_numpy()
Ymin = cars["Start Y"].to_numpy()
W = cars["W"].to_numpy()
H = cars["H"].to_numpy()

In [28]:
Xmax = np.add(Xmin, W)
Ymax = np.add(Ymin, H)

In [29]:
data = zip(Xmin, Ymin, Xmax, Ymax)
data = list(data)
cars["data"] = data

In [30]:
data = np.array(data)

In [31]:
cars

           filename  Start X  Start Y    W    H                 data
0      2Q__ (1).jpg        1       26   97   49      (1, 26, 98, 75)
1      2Q__ (3).jpg        5       11  296  120    (5, 11, 301, 131)
2      2Q__ (4).jpg       22       27  223  142   (22, 27, 245, 169)
3      2Q__ (5).jpg       33       15  246  127   (33, 15, 279, 142)
4      2Q__ (6).jpg       13       42  233  124   (13, 42, 246, 166)
5       9k_ (2).jpg        4       55  217  141    (4, 55, 221, 196)
6       9k_ (3).jpg       22       18  228  128   (22, 18, 250, 146)
7       9k_ (4).jpg       35       29  229  124   (35, 29, 264, 153)
8       9k_ (6).jpg       19       37  234  116   (19, 37, 253, 153)
9       9k_ (7).jpg       24       57  205  101   (24, 57, 229, 158)
10      9k_ (8).jpg       15       13  262  145   (15, 13, 277, 158)
11     9k_ (10).jpg       70       24  196  106   (70, 24, 266, 130)
12     9k_ (11).jpg       57       51  161  101   (57, 51, 218, 152)
13  images (18).jpg       38       34  254  113   (38, 34, 292, 147)
14  images (19).jpg       46       52  185  110   (46, 52, 231, 162)
15  images (20).jpg       23       18  228  116   (23, 18, 251, 134)
16  images (21).jpg       85       49  158   92   (85, 49, 243, 141)
17  images (22).jpg       42      104  157  110  (42, 104, 199, 214)
18  images (23).jpg       42       32  214  114   (42, 32, 256, 146)
19  images (24).jpg        9       23  259  154    (9, 23, 268, 177)
20  images (25).jpg       19        9  222  163    (19, 9, 241, 172)
21  images (26).jpg       78       37  211  116   (78, 37, 289, 153)
22  images (28).jpg       17       20  276  120   (17, 20, 293, 140)
23  images (29).jpg       49        2  239  158    (49, 2, 288, 160)
24  images (31).jpg       73        8  192  139    (73, 8, 265, 147)
25  images (32).jpg        6       11  284  143    (6, 11, 290, 154)
26  images (34).jpg       10       72  206  102   (10, 72, 216, 174)
27  images (35).jpg       42       45  212  112   (42, 45, 254, 157)
28  images (37).jpg       21       37  232  121   (21, 37, 253, 158)
29  images (38).jpg       14       16  267  142   (14, 16, 281, 158)
30  images (39).jpg       23       44  179  111   (23, 44, 202, 155)
31  images (40).jpg       49       42  198  109   (49, 42, 247, 151)
32        Z (6).jpg       32       21  253  123   (32, 21, 285, 144)
33        Z (7).jpg       28       35  224  133   (28, 35, 252, 168)
34        Z (8).jpg       27       34  209  105   (27, 34, 236, 139)

In [32]:
DATADIR = r"C:\Users\Carlos M\Pictures"
CATEGORIES = ["cars"]
training_data = list()
Xmin = cars["Start X"].to_numpy()
print(Xmin.shape)
Ymin = cars["Start Y"].to_numpy()
Xmax = np.add(Xmin, W)
Ymax = np.add(Ymin, H)
width = list()
length = list()
def create_training_data():
    for category in CATEGORIES:
        path = os.path.join(DATADIR, category)
        class_num = CATEGORIES.index(category)
        for img in os.listdir(path):
            try:
                img = cv2.imread(os.path.join(path, img))
                img_array = img / 255.0
                img_width = img_array.shape[0]
                img_length = img_array.shape[1]
                width.append(img_width)
                length.append(img_length)
                new_array = cv2.resize(img_array, (224, 224))
                training_data.append([new_array, class_num])
            except Exception as e:
                pass

create_training_data()
X = list()
Y = list()
for features, label in training_data:
    X.append(features)
    Y.append(label)

width = np.array(width)
length = np.array(length)
    
X = np.array(X).reshape(-3, 224, 224, 3)
print(X.shape)
Y = np.array(Y)

ratio_Xmin = np.divide(Xmin, length)
ratio_Ymin = np.divide(Ymin, width)
ratio_Xmax = np.divide(Xmax, length)
ratio_Ymax = np.divide(Ymax, width)

# Were training the CNN on the ratio of value of Xmin, Ymin, Xmax, Ymax
# aka bound box points in relation to the image width and length

(35,)
(35, 224, 224, 3)

In [33]:
vgg = VGG16(weights="imagenet", include_top=False, input_tensor=Input(shape=(224, 224, 3)))
vgg.trainable = False
flatten = vgg.output
flatten = Flatten()(flatten)
bboxHead = Dense(128, activation="relu")(flatten)
bboxHead = Dense(64, activation="relu")(bboxHead)
bboxHead = Dense(32, activation="relu")(bboxHead)
bboxHead = Dense(4, activation="sigmoid")(bboxHead)

# construct the model we will fine-tune for bounding box regression
model = Model(inputs=vgg.input, outputs=bboxHead)

# initialize the optimizer, compile the model, and show the model
# summary
opt = Adam(lr=0.001)
model.compile(loss="mse", optimizer=opt)
print(model.summary())

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_2 (InputLayer)         [(None, 224, 224, 3)]     0
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0
_________________________________________________________________
block3_conv1 (Conv2D)        (None, 56, 56, 256)       295168
_________________________________________________________________
block3_conv2 (Conv2D)        (None, 56, 56, 256)       590080
_________________________________________________________________
block3_conv3 (Conv2D)        (None, 56, 56, 256)       590080
_________________________________________________________________
block3_pool (MaxPooling2D)   (None, 28, 28, 256)       0
_________________________________________________________________
block4_conv1 (Conv2D)        (None, 28, 28, 512)       1180160
_________________________________________________________________
block4_conv2 (Conv2D)        (None, 28, 28, 512)       2359808
_________________________________________________________________
block4_conv3 (Conv2D)        (None, 28, 28, 512)       2359808
_________________________________________________________________
block4_pool (MaxPooling2D)   (None, 14, 14, 512)       0
_________________________________________________________________
block5_conv1 (Conv2D)        (None, 14, 14, 512)       2359808
_________________________________________________________________
block5_conv2 (Conv2D)        (None, 14, 14, 512)       2359808
_________________________________________________________________
block5_conv3 (Conv2D)        (None, 14, 14, 512)       2359808
_________________________________________________________________
block5_pool (MaxPooling2D)   (None, 7, 7, 512)         0
_________________________________________________________________
flatten_1 (Flatten)          (None, 25088)             0
_________________________________________________________________
dense_4 (Dense)              (None, 128)               3211392
_________________________________________________________________
dense_5 (Dense)              (None, 64)                8256
_________________________________________________________________
dense_6 (Dense)              (None, 32)                2080
_________________________________________________________________
dense_7 (Dense)              (None, 4)                 132
=================================================================
Total params: 17,936,548
Trainable params: 3,221,860
Non-trainable params: 14,714,688
_________________________________________________________________
None

In [34]:
data = zip(ratio_Xmin, ratio_Ymin, ratio_Xmax, ratio_Ymax)
data = list(data)
data = np.array(data)

In [35]:
model.fit(X, data, epochs = 2, validation_split = 0.3)

Train on 24 samples, validate on 11 samples
Epoch 1/2
24/24 [==============================] - 2s 96ms/sample - loss: 0.2650 - val_loss: 0.1212
Epoch 2/2
24/24 [==============================] - 2s 67ms/sample - loss: 0.1289 - val_loss: 0.0089

In [36]:
imagepath = r"C:\Users\Carlos M\Pictures\Demon.jpg"
image = cv2.imread(imagepath)
image = image / 255.0
image = cv2.resize(image, (224, 224))
print(image.shape)
image = np.expand_dims(image, axis = 0)
preds = model.predict(image)[0]
(startX, startY, endX, endY) = preds
startX = int(startX * 224)
startY = int(startY * 224)
endX = int(endX * 224)
endY = int(endY * 224)
print([startX, startY, endX, endY])

(224, 224, 3)
[12, 30, 178, 189]

In [37]:
image = cv2.imread(imagepath)
image = cv2.resize(image, (224, 224))

In [39]:
cv2.rectangle(image, (startX, startY), (endX, endY), (0, 255, 0), 2)
cv2.imshow("Output", image)
cv2.waitKey(0)
cv2.destroyAllWindows()